#!/bin/bash

title="(sche)"
schefile="$HOME/.config/sche/config.txt"
curtime=$(date +"%H.%M") # hour.minutes
stime=$((60)) # sleep_time; default: 1 minute

if [[ -z "$1" || "$1" == "-h" || "$1" == "--help" ]]; then
    echo "Usage: sche <none> [s|start] [w|write] [a|all]"

elif [[ "$1" == "s" || "$1" == "start" ]]; then
    while :; do
        # echo "[sche started]"
        # if notify-send is above the sleep, it will send a notification as soon as it starts
        loadm="$(cat "$schefile" | grep "$curtime:" )"
        
        if [ -z "$loadm" ]; then
            loadm="$(cat "$schefile" | grep "$(date +"%H"):")"
        fi
        sleep 3600
        notify-send -t 1800000 "Sche" "$(cat "$schefile" | grep "$curtime:" )"
    done

elif [[ "$1" == "a" || "$1" == "all" ]]; then
    cat "$schefile" | grep -v "#" | grep .

elif [[ "$1" == "w" || "$1" == "write" ]]; then
    $EDITOR $schefile
fi

# else: just exit with no output

